<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
<<<<<<< HEAD
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
=======
    'app_accueil_accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::Accueil'], [], [['text', '/accueil']], [], []],
    'app_accueil_new' => [[], ['_controller' => 'App\\Controller\\AccueilController::new'], [], [['text', '/accueil/register']], [], []],
    'app_index_index' => [[], ['_controller' => 'App\\Controller\\IndexController::Index'], [], [['text', '/index']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/authentication/logout']], [], []],
>>>>>>> 9a0057f42942eea01086beac3fe966b720039a79
];
